### ISSUE TITLE
Keyspace system_views  related table not able to select with cassandra-lucene-index-plugin-4.1.0-1.0.0.jar

### ISSUE THREAD

**Issue by Sreemanth** [instaclustr/cassandra-lucene-index#16]
**CQL Query**
```cql
 select * from system_views.settings;

```

Error in CQL

```
NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.0.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="java.lang.IllegalStateException: Cannot initialize Keyspace with virtual metadata system_views">})
```

**Error in system.log file**
```java
ERROR [Native-Transport-Requests-1] 2023-06-01 15:55:28,514 QueryMessage.java:129 - Unexpected error during query
java.lang.IllegalStateException: Cannot initialize Keyspace with virtual metadata system_views
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:342)
	at org.apache.cassandra.db.Keyspace.lambda$open$0(Keyspace.java:163)
	at org.apache.cassandra.utils.concurrent.LoadingMap.blockingLoadIfAbsent(LoadingMap.java:105)
	at org.apache.cassandra.schema.Schema.maybeAddKeyspaceInstance(Schema.java:230)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:163)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:152)
	at com.stratio.cassandra.lucene.IndexQueryHandler.luceneExpressions(IndexQueryHandler.scala:129)
	at com.stratio.cassandra.lucene.IndexQueryHandler.processStatement(IndexQueryHandler.scala:103)
	at com.stratio.cassandra.lucene.IndexQueryHandler.process(IndexQueryHandler.scala:91)
	at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116)
	at org.apache.cassandra.transport.Message$Request.execute(Message.java:254)
	at org.apache.cassandra.transport.Dispatcher.processRequest(Dispatcher.java:122)
	at org.apache.cassandra.transport.Dispatcher.processRequest(Dispatcher.java:141)
	at org.apache.cassandra.transport.Dispatcher.processRequest(Dispatcher.java:168)
	at org.apache.cassandra.transport.Dispatcher.lambda$dispatch$0(Dispatcher.java:82)
	at org.apache.cassandra.concurrent.FutureTask$1.call(FutureTask.java:81)
	at org.apache.cassandra.concurrent.FutureTask.call(FutureTask.java:47)
	at org.apache.cassandra.concurrent.FutureTask.run(FutureTask.java:57)
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:120)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
ERROR [Native-Transport-Requests-1] 2023-06-01 15:55:28,515 ErrorMessage.java:457 - Unexpected exception during request
java.lang.IllegalStateException: Cannot initialize Keyspace with virtual metadata system_views
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:342)
	at org.apache.cassandra.db.Keyspace.lambda$open$0(Keyspace.java:163)
	at org.apache.cassandra.utils.concurrent.LoadingMap.blockingLoadIfAbsent(LoadingMap.java:105)
	at org.apache.cassandra.schema.Schema.maybeAddKeyspaceInstance(Schema.java:230)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:163)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:152)
	at com.stratio.cassandra.lucene.IndexQueryHandler.luceneExpressions(IndexQueryHandler.scala:129)
	at com.stratio.cassandra.lucene.IndexQueryHandler.processStatement(IndexQueryHandler.scala:103)
	at com.stratio.cassandra.lucene.IndexQueryHandler.process(IndexQueryHandler.scala:91)
	at org.apache.cassandra.transport.messages.QueryMessage.execute(QueryMessage.java:116)
	at org.apache.cassandra.transport.Message$Request.execute(Message.java:254)
	at org.apache.cassandra.transport.Dispatcher.processRequest(Dispatcher.java:122)
	at org.apache.cassandra.transport.Dispatcher.processRequest(Dispatcher.java:141)
	at org.apache.cassandra.transport.Dispatcher.processRequest(Dispatcher.java:168)
	at org.apache.cassandra.transport.Dispatcher.lambda$dispatch$0(Dispatcher.java:82)
	at org.apache.cassandra.concurrent.FutureTask$1.call(FutureTask.java:81)
	at org.apache.cassandra.concurrent.FutureTask.call(FutureTask.java:47)
	at org.apache.cassandra.concurrent.FutureTask.run(FutureTask.java:57)
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:120)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by smiklosovic** [comment]
@Sreemanth this is unfixable. This is directly in Cassandra (1)

We can not open Keyspace differently than here (2)

Using this plugin against virtual tables is not supported.

(1) https://github.com/apache/cassandra/blob/cassandra-4.1/src/java/org/apache/cassandra/db/Keyspace.java#L341-L342
(2) https://github.com/instaclustr/cassandra-lucene-index/blob/cassandra-4.1.0/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexQueryHandler.scala#L129

**Comment by bschoening** [comment]
@smiklosovic should (2) above skip system_views?  It  already skips system_virtual_scheam:

`    if (select.keyspace() == "system_virtual_schema") {
      return Map.empty
    }`

**Comment by smiklosovic** [comment]
Ah yes, interesting, I overlooked that.

I merged it here (1), into cassandra-4.1.3. Should be easily cherry-picked to lower branches too.

(1) https://github.com/instaclustr/cassandra-lucene-index/commit/994f470b00220a05ffe078d93d5c2b7a614a9b66
